#!/bin/sh

HOST=$1
BASEDIR=$2
NUM=$3

teamname="HELIOS_base"

player="./src/sample_player"
coach="./src/sample_coach"

config="src/player.conf"
config_dir="src/formations-dt"
coach_config="src/coach.conf"

opt="--player-config ${config} --config_dir ${config_dir}"
opt="${opt} -h ${HOST} -t ${teamname}"

coachopt="--coach-config ${coach_config}"
coachopt="${coachopt} -h ${HOST} -t ${teamname}"

cd $BASEDIR

case $NUM in
    1)
        $player $opt -g
        ;;
    12)
        $coach $coachopt
        ;;
    *)
        $player $opt
        ;;
esac
