---
mode: group
title: RoboCup 2010 First Round, Group D
server_conf: config/rcssserver/server_official.conf
player_conf: config/rcssserver/player_official.conf
teams_dir: /home/
log_dir: log/robocup2010/groups/group_D
teams:
  - helios
  - opuci
  - fcpars
  - rione
  - kickofftug
